import { IncidentStatus } from '@prisma/client';

export const decisions: Record<string, IncidentStatus> = {
  SITE_VISIT: 'IN_PROGRESS', INSPECTION_COMPLETED: 'IN_PROGRESS', MONITORING: 'IN_PROGRESS',
  MAINTENANCE_SCHEDULED: 'IN_PROGRESS', REPAIR_COMPLETED: 'RESOLVED', OTHER: 'IN_PROGRESS',
  DISPATCH_EMERGENCY_TEAM: 'IN_PROGRESS', EQUIPMENT_SHUTDOWN: 'IN_PROGRESS',
  REMOTE_DIAGNOSTICS: 'IN_PROGRESS', INSPECTION_SCHEDULED: 'IN_PROGRESS',
  ACKNOWLEDGE: 'IN_PROGRESS', CONFIRM_INCIDENT: 'CONFIRMED', FALSE_ALARM: 'FALSE_POSITIVE',
};
export const reasons = ['SENSOR_CHECK', 'VIDEO_CHECK', 'PLANNED_WORK', 'SITE_INSPECTION', 'OTHER'] as const;
