// Generated by scripts/build_state_reference.py; preserve source conflicts.
// Source SHA256: b968f3652ed33fd6e0d2dccee334275436dada67f4549763cfb4b2072108b5cc
export const sensorStates = [
  {
    "sensorType": "КД Дверь",
    "stateSetId": 1,
    "state": "Норма",
    "alarm": false,
    "sourceLine": 2
  },
  {
    "sensorType": "КД Дверь",
    "stateSetId": 1,
    "state": "Выключен",
    "alarm": false,
    "sourceLine": 3
  },
  {
    "sensorType": "КД Дверь",
    "stateSetId": 1,
    "state": "Отключено устройство",
    "alarm": true,
    "sourceLine": 4
  },
  {
    "sensorType": "КД Дверь",
    "stateSetId": 2,
    "state": "Норма",
    "alarm": false,
    "sourceLine": 5
  },
  {
    "sensorType": "КД Дверь",
    "stateSetId": 2,
    "state": "Замкнут",
    "alarm": true,
    "sourceLine": 6
  },
  {
    "sensorType": "КД Люк",
    "stateSetId": 3,
    "state": "Не замкнут",
    "alarm": true,
    "sourceLine": 7
  },
  {
    "sensorType": "КД Люк",
    "stateSetId": 3,
    "state": "Норма",
    "alarm": false,
    "sourceLine": 8
  },
  {
    "sensorType": "КД Люк",
    "stateSetId": 4,
    "state": "Включен",
    "alarm": false,
    "sourceLine": 9
  },
  {
    "sensorType": "КД Люк",
    "stateSetId": 4,
    "state": "Выключен",
    "alarm": false,
    "sourceLine": 10
  },
  {
    "sensorType": "КД АВ",
    "stateSetId": 5,
    "state": "Дыма нет",
    "alarm": false,
    "sourceLine": 11
  },
  {
    "sensorType": "КД АВ",
    "stateSetId": 5,
    "state": "Обнаружен дым",
    "alarm": true,
    "sourceLine": 12
  },
  {
    "sensorType": "КД АВ",
    "stateSetId": 6,
    "state": "Движения нет",
    "alarm": false,
    "sourceLine": 13
  },
  {
    "sensorType": "КД АВ",
    "stateSetId": 6,
    "state": "Обнаружено движение",
    "alarm": true,
    "sourceLine": 14
  },
  {
    "sensorType": "КД АВ",
    "stateSetId": 6,
    "state": "Движение вверх",
    "alarm": true,
    "sourceLine": 15
  },
  {
    "sensorType": "КД АВ",
    "stateSetId": 6,
    "state": "Движение вниз",
    "alarm": true,
    "sourceLine": 16
  },
  {
    "sensorType": "КД АВ",
    "stateSetId": 6,
    "state": "Движение влево",
    "alarm": true,
    "sourceLine": 17
  },
  {
    "sensorType": "КД АВ",
    "stateSetId": 6,
    "state": "Движение вправо",
    "alarm": true,
    "sourceLine": 18
  },
  {
    "sensorType": "Датчик температуры",
    "stateSetId": 7,
    "state": "Норма",
    "alarm": false,
    "sourceLine": 19
  },
  {
    "sensorType": "Датчик температуры",
    "stateSetId": 7,
    "state": "Обнаружен газ",
    "alarm": true,
    "sourceLine": 20
  },
  {
    "sensorType": "Датчик движения",
    "stateSetId": 8,
    "state": "Выключен",
    "alarm": false,
    "sourceLine": 21
  },
  {
    "sensorType": "Датчик движения",
    "stateSetId": 8,
    "state": "Включен",
    "alarm": false,
    "sourceLine": 22
  },
  {
    "sensorType": "Датчик движения",
    "stateSetId": 8,
    "state": "Затоплен",
    "alarm": true,
    "sourceLine": 23
  },
  {
    "sensorType": "Датчик движения",
    "stateSetId": 8,
    "state": "Обесточен",
    "alarm": true,
    "sourceLine": 24
  },
  {
    "sensorType": "Датчик движения",
    "stateSetId": 9,
    "state": "Выключен",
    "alarm": false,
    "sourceLine": 25
  },
  {
    "sensorType": "Датчик движения",
    "stateSetId": 9,
    "state": "Включен",
    "alarm": false,
    "sourceLine": 26
  },
  {
    "sensorType": "Датчик движения",
    "stateSetId": 9,
    "state": "Обесточен",
    "alarm": true,
    "sourceLine": 27
  },
  {
    "sensorType": "Датчик дыма",
    "stateSetId": 11,
    "state": "Рычаг норма",
    "alarm": false,
    "sourceLine": 28
  },
  {
    "sensorType": "Газовый датчик",
    "stateSetId": 12,
    "state": "Норма",
    "alarm": false,
    "sourceLine": 29
  },
  {
    "sensorType": "Газовый датчик",
    "stateSetId": 12,
    "state": "Разговор",
    "alarm": false,
    "sourceLine": 30
  },
  {
    "sensorType": "Газовый датчик",
    "stateSetId": 12,
    "state": "Вызов",
    "alarm": false,
    "sourceLine": 31
  },
  {
    "sensorType": "КД Дверь",
    "stateSetId": 1,
    "state": "Неопределен",
    "alarm": false,
    "sourceLine": 32
  },
  {
    "sensorType": "КД Дверь",
    "stateSetId": 1,
    "state": "Неисправен",
    "alarm": true,
    "sourceLine": 33
  },
  {
    "sensorType": "Состояние вентилятора",
    "stateSetId": 16,
    "state": "Питание от сети",
    "alarm": false,
    "sourceLine": 34
  },
  {
    "sensorType": "Состояние насоса",
    "stateSetId": 14,
    "state": "На охране",
    "alarm": false,
    "sourceLine": 35
  },
  {
    "sensorType": "Состояние насоса",
    "stateSetId": 14,
    "state": "Снято с охраны",
    "alarm": false,
    "sourceLine": 36
  },
  {
    "sensorType": "Состояние вентилятора",
    "stateSetId": 16,
    "state": "Питание от батарей",
    "alarm": true,
    "sourceLine": 37
  },
  {
    "sensorType": "Датчик дыма",
    "stateSetId": 11,
    "state": "Рычаг сдернут",
    "alarm": true,
    "sourceLine": 38
  },
  {
    "sensorType": "Датчик дыма",
    "stateSetId": 11,
    "state": "Рычаг сдернут влево",
    "alarm": true,
    "sourceLine": 39
  },
  {
    "sensorType": "Датчик дыма",
    "stateSetId": 11,
    "state": "Рычаг сдернут вправо",
    "alarm": true,
    "sourceLine": 40
  },
  {
    "sensorType": "Датчик дыма",
    "stateSetId": 11,
    "state": "Оба рычага сдернуты",
    "alarm": true,
    "sourceLine": 41
  },
  {
    "sensorType": "Состояние вентилятора",
    "stateSetId": 16,
    "state": "Батарея неисправна",
    "alarm": false,
    "sourceLine": 42
  },
  {
    "sensorType": "Датчик дыма",
    "stateSetId": 10,
    "state": "Есть питание",
    "alarm": false,
    "sourceLine": 43
  },
  {
    "sensorType": "Датчик дыма",
    "stateSetId": 10,
    "state": "Обесточен",
    "alarm": false,
    "sourceLine": 44
  },
  {
    "sensorType": "Состояние вентилятора",
    "stateSetId": 17,
    "state": "Устройства на объекте исправны",
    "alarm": false,
    "sourceLine": 45
  },
  {
    "sensorType": "Состояние вентилятора",
    "stateSetId": 17,
    "state": "Много неисправных устройств",
    "alarm": true,
    "sourceLine": 46
  },
  {
    "sensorType": "Состояние вентилятора",
    "stateSetId": 16,
    "state": "Батарея разряжена",
    "alarm": true,
    "sourceLine": 47
  },
  {
    "sensorType": "Состояние фазы",
    "stateSetId": 18,
    "state": "Работают все насосы АНС",
    "alarm": true,
    "sourceLine": 48
  },
  {
    "sensorType": "Состояние вентилятора",
    "stateSetId": 17,
    "state": "Включены все насосы АНС",
    "alarm": true,
    "sourceLine": 49
  },
  {
    "sensorType": "Датчик движения",
    "stateSetId": 8,
    "state": "Работают все насосы в АНС",
    "alarm": true,
    "sourceLine": 50
  },
  {
    "sensorType": "Газовый датчик",
    "stateSetId": 13,
    "state": "Температура выше 35ºC1",
    "alarm": true,
    "sourceLine": 51
  },
  {
    "sensorType": "Газовый датчик",
    "stateSetId": 13,
    "state": "Температура выше 35ºC1",
    "alarm": true,
    "sourceLine": 52
  },
  {
    "sensorType": "Газовый датчик",
    "stateSetId": 13,
    "state": "В норме от +3 до +351",
    "alarm": false,
    "sourceLine": 53
  },
  {
    "sensorType": "Газовый датчик",
    "stateSetId": 13,
    "state": "Температура ниже 3ºC1",
    "alarm": false,
    "sourceLine": 54
  },
  {
    "sensorType": "Газовый датчик",
    "stateSetId": 13,
    "state": "Температура ниже 3ºC1",
    "alarm": true,
    "sourceLine": 55
  },
  {
    "sensorType": "Газовый датчик",
    "stateSetId": 13,
    "state": "Температура ниже 3ºC",
    "alarm": true,
    "sourceLine": 56
  },
  {
    "sensorType": "Газовый датчик",
    "stateSetId": 13,
    "state": "Не определено",
    "alarm": true,
    "sourceLine": 57
  },
  {
    "sensorType": "Газовый датчик",
    "stateSetId": 13,
    "state": "Температура ниже 3ºC1",
    "alarm": true,
    "sourceLine": 58
  },
  {
    "sensorType": "Газовый датчик",
    "stateSetId": 13,
    "state": "В норме от +3 до +40",
    "alarm": false,
    "sourceLine": 59
  },
  {
    "sensorType": "Газовый датчик",
    "stateSetId": 13,
    "state": "Температура выше 40ºC",
    "alarm": true,
    "sourceLine": 60
  },
  {
    "sensorType": "Газовый датчик",
    "stateSetId": 13,
    "state": "Температура ниже 3ºC",
    "alarm": true,
    "sourceLine": 61
  },
  {
    "sensorType": "Газовый датчик",
    "stateSetId": 13,
    "state": "В норме от +3 до +27ºC",
    "alarm": false,
    "sourceLine": 62
  },
  {
    "sensorType": "Газовый датчик",
    "stateSetId": 13,
    "state": "Температура выше 27ºC",
    "alarm": true,
    "sourceLine": 63
  }
];
