"""Compile the supplied state dictionary without correcting or discarding source rows."""
import csv
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = ROOT / 'docs/sources/chat-20260928/sensor-states.csv'
with source.open(encoding='utf-8-sig', newline='') as stream:
    rows = []
    for line, row in enumerate(csv.DictReader(stream), 2):
        assert row['тревожное'] in ('true', 'false'), f'Invalid flag at line {line}'
        rows.append(dict(sensorType=row['тип_датчика'], stateSetId=int(row['ид_набор_состояний']),
                         state=row['название_состояния'], alarm=row['тревожное'] == 'true', sourceLine=line))
target = ROOT / 'server/src/services/sensorStates.generated.ts'
target.write_text('// Generated by scripts/build_state_reference.py; preserve source conflicts.\n'
                  f'// Source SHA256: {hashlib.sha256(source.read_bytes()).hexdigest()}\n'
                  + 'export const sensorStates = ' + json.dumps(rows, ensure_ascii=False, indent=2)
                  + ';\n', encoding='utf-8')
print(f'Compiled {len(rows)} source rows')
